%define FORE_BLACK              0x1b, "[30m"
%define FORE_RED                0x1b, "[31m"
%define FORE_GREEN              0x1b, "[32m"
%define FORE_YELLOW             0x1b, "[33m"
%define FORE_BLUE               0x1b, "[34m"
%define FORE_MAGENTA            0x1b, "[35m"
%define FORE_CYAN               0x1b, "[36m"
%define FORE_WHITE              0x1b, "[37m"
%define FORE_RESET              0x1b, "[39m"

%define FORE_LIGHT_BLACK        0x1b, "[90m"
%define FORE_LIGHT_RED          0x1b, "[91m"
%define FORE_LIGHT_GREEN        0x1b, "[92m"
%define FORE_LIGHT_YELLOW       0x1b, "[93m"
%define FORE_LIGHT_BLUE         0x1b, "[94m"
%define FORE_LIGHT_MAGENTA      0x1b, "[95m"
%define FORE_LIGHT_CYAN         0x1b, "[96m"
%define FORE_LIGHT_WHITE        0x1b, "[97m"

%define BACK_BLACK              0x1b, "[40m"
%define BACK_RED                0x1b, "[41m"
%define BACK_GREEN              0x1b, "[42m"
%define BACK_YELLOW             0x1b, "[43m"
%define BACK_BLUE               0x1b, "[44m"
%define BACK_MAGENTA            0x1b, "[45m"
%define BACK_CYAN               0x1b, "[46m"
%define BACK_WHITE              0x1b, "[47m"
%define BACK_RESET              0x1b, "[49m"

%define BACK_LIGHT_BLACK        0x1b, "[100m"
%define BACK_LIGHT_RED          0x1b, "[101m"
%define BACK_LIGHT_GREEN        0x1b, "[102m"
%define BACK_LIGHT_YELLOW       0x1b, "[103m"
%define BACK_LIGHT_BLUE         0x1b, "[104m"
%define BACK_LIGHT_MAGENTA      0x1b, "[105m"
%define BACK_LIGHT_CYAN         0x1b, "[106m"
%define BACK_LIGHT_WHITE        0x1b, "[107m"

%define STYLE_BRIGHT            0x1b, "[1m"
%define STYLE_DIM               0x1b, "[2m"
%define STYLE_NORMAL            0x1b, "[22m"
%define STYLE_RESET_ALL         0x1b, "[0m"
